[project]
classifiers = [
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
]
name = "nomad-distribution"
description = "nomad distribution template"
dynamic = ["version"]
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
dependencies = [
  "nomad-lab[infrastructure, parsing]>=1.3.0",
  "pybis @ git+https://github.com/FAIRmat-NFDI/fairmat-pybis.git@91039c2a1df364c88ab7e284b59c43ec42f18370",
]

[project.optional-dependencies]
plugins = [
  "nomad-sintering @ git+https://github.com/hampusnasstrom/nomad-sintering.git",
  "nomad-measurements @ git+https://github.com/FAIRmat-NFDI/nomad-measurements@main",
  "nomad-material-processing @ git+https://github.com/FAIRmat-NFDI/nomad-material-processing@main",
  "nomad-catalysis @ git+https://github.com/schumannj/nomad-schema-plugin-fhi-catalysis@main",
  "nomad-analysis @ git+https://github.com/FAIRmat-NFDI/nomad-analysis@develop",
  "uv-vis-nir-transmission @ git+https://github.com/FAIRmat-NFDI/AreaA-data_modeling_and_schemas.git@f53390fc1a4b80fa4d9e7ebbe4516f461f54ed61#subdirectory=transmission/transmission_plugin/uv_vis_nir_transmission_plugin",
]
dev = ["pytest"]

[tool.uv.pip]
index-url = "https://gitlab.mpcdf.mpg.de/api/v4/projects/2187/packages/pypi/simple"

[tool.setuptools.packages.find]
exclude = ["gui*", "docs*", "config*"]
[tool.setuptools_scm]
