name: update lock file

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_lockfile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hynek/setup-cached-uv@v1

      - name: update lock file
        run: ./scripts/generate_python_dependencies.sh

      # Commits all changes
      - name: Commit repository initialization
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add requirements*
          git commit -m "Update lockfile"
          git push
