name: update lock file

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_lockfile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - uses: hynek/setup-cached-uv@v1

      - name: update lock file
        run: ./scripts/generate_python_dependencies.sh

      # Commits all changes
      - name: Commit repository initialization
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add requirements*
          if [[ `git status --porcelain` ]]; then
            git commit -m "Update lockfile"
            git push
          fi
